### ISSUE TITLE
Doesn't not model ore in the hand and in inventory 1.12.2

### ISSUE THREAD

**Issue by ghost** [McJty/YouTubeModdingTutorial#6]
![ScreenShot_20190625003500](https://user-images.githubusercontent.com/37004902/60056276-d2d97300-96f9-11e9-81c1-bd6b891285ac.jpeg)

**Comment by ghost** [comment]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.getVariant(ModelBlockDefinition.java:83) ~[ModelBlockDefinition.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1175) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) ~[ModelLoaderRegistry.class:?]
	... 20 more

**Comment by ghost** [comment]
Version forge 14.23.5.2768
